---
apiVersion: v1
kind: Namespace
metadata:
  name: fapp1
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: fapp1
  labels:
    role: web-service
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: fapp1
  labels:
    role: web-service
spec:
  selector:
    role: web-service
  type: NodePort
  ports:
  - port: 80
    nodePort: 32001
